### ISSUE TITLE
Statues/Scarecrows are hard to break.

### ISSUE THREAD

**Issue by starlikestylus** [aqariio/furnishings#1]
It's very hard to break the scarecrows and its virtually impossible to break the statues in survival so maybe make it so statues and scarecrows can break like how boats, armour stands, etc do?

**Comment by aqariio** [comment]
Statues and scarecrows are broken with pickaxes and axes respectively while sneaking, which means that you can attack them normally and not break them on accident. Sorry for not making this information clear, I'm still working on the mod!
Btw statues and scarecrows can be a little buggy as they're not finished yet.
